package com.demo.entities;
// Generated Jan 8, 2019 7:30:02 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Invoicedetail generated by hbm2java
 */
@Entity
@Table(name = "invoicedetail", catalog = "demo_buoi_10")
public class Invoicedetail implements java.io.Serializable {

	private InvoicedetailId id;
	private Invoice invoice;
	private Product product;
	private double price;
	private int quantity;

	public Invoicedetail() {
	}

	public Invoicedetail(InvoicedetailId id, Invoice invoice, Product product, double price, int quantity) {
		this.id = id;
		this.invoice = invoice;
		this.product = product;
		this.price = price;
		this.quantity = quantity;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "ProductId", nullable = false)),
			@AttributeOverride(name = "invoiceId", column = @Column(name = "InvoiceId", nullable = false)) })
	public InvoicedetailId getId() {
		return this.id;
	}

	public void setId(InvoicedetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InvoiceId", nullable = false, insertable = false, updatable = false)
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductId", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "Price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
