package com.demo.entities;
// Generated Jan 8, 2019 7:30:02 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoicedetailId generated by hbm2java
 */
@Embeddable
public class InvoicedetailId implements java.io.Serializable {

	private int productId;
	private int invoiceId;

	public InvoicedetailId() {
	}

	public InvoicedetailId(int productId, int invoiceId) {
		this.productId = productId;
		this.invoiceId = invoiceId;
	}

	@Column(name = "ProductId", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "InvoiceId", nullable = false)
	public int getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(int invoiceId) {
		this.invoiceId = invoiceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoicedetailId))
			return false;
		InvoicedetailId castOther = (InvoicedetailId) other;

		return (this.getProductId() == castOther.getProductId()) && (this.getInvoiceId() == castOther.getInvoiceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getInvoiceId();
		return result;
	}

}
