package com.demo.entities;
// Generated Jan 8, 2019 7:30:02 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", catalog = "demo_buoi_10")
public class Invoice implements java.io.Serializable {

	private Integer id;
	private String name;
	private String payment;
	private Integer status;
	private Set<Invoicedetail> invoicedetails = new HashSet<Invoicedetail>(0);

	public Invoice() {
	}

	public Invoice(String name, String payment, Integer status, Set<Invoicedetail> invoicedetails) {
		this.name = name;
		this.payment = payment;
		this.status = status;
		this.invoicedetails = invoicedetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Payment", length = 250)
	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
	public Set<Invoicedetail> getInvoicedetails() {
		return this.invoicedetails;
	}

	public void setInvoicedetails(Set<Invoicedetail> invoicedetails) {
		this.invoicedetails = invoicedetails;
	}

}
